template_version: 6
strategy: adaptive_market_making
# Exchange and markets
exchange: binance
market: ETH-BTC

# Strategy parameters
min_spread: 0.002
max_spread: 0.01
order_amount: 0.1
order_refresh_time: 60.0
max_order_age: 600.0

# Technical indicator parameters
rsi_length: 14
ema_short: 12
ema_long: 26
bb_length: 20

# Risk management parameters
max_inventory_ratio: 0.5
min_inventory_ratio: 0.3
volatility_adjustment: 1.0
max_position_value: 5.0
trailing_stop_pct: 0.02

# Backtesting parameters
start_time: 2022-09-01
end_time: 2023-09-01
simulate_exchange_connection: true

# Fee structure
exchange_fee_rate: 0.001  # 0.1% fee 