template_version: 9

strategy: adaptive_market_making
exchange: binance  # replace with your exchange of choice
market: ETH-USDT  # replace with your trading pair of choice

# Order Parameters
order_amount: 0.1  # Amount of base asset per order
min_spread: 0.002  # Minimum spread (0.2%)
max_spread: 0.02   # Maximum spread (2.0%)
order_refresh_time: 30.0  # How often to refresh orders (in seconds)
max_order_age: 300.0  # Maximum lifetime of an order (in seconds)

# Technical Indicator Parameters
rsi_length: 14
rsi_overbought: 70
rsi_oversold: 30
ema_short: 12
ema_long: 26
bb_length: 20
bb_std: 2.0

# Risk Management Parameters
max_inventory_ratio: 0.5  # Maximum allowed base asset as a % of total portfolio value
volatility_adjustment: 1.0  # Multiplier for volatility-based spread adjustments

# Additional Parameters (optional)
status_report_interval: 900.0  # How often to report status (in seconds) 