template_version: 8

strategy: adaptive_market_making
exchange: binance_paper_trade
market: ETH-USDT

# Basic market making parameters
order_amount: 0.1
min_spread: 0.1
max_spread: 1.0
order_refresh_time: 30.0
max_order_age: 3600.0

# Technical indicator parameters
rsi_length: 14
rsi_overbought: 70
rsi_oversold: 30
ema_short: 12
ema_long: 120
bb_length: 20
bb_std: 2.0

# Risk management parameters
target_inventory_ratio: 0.5
min_order_amount: 0.01
volatility_adjustment: 1.0
trailing_stop_pct: 2.0
signal_threshold: 50 