name: hummingbot
channels:
  - conda-forge
  - defaults
dependencies:
  ### Packages needed for the build/install process
  # - bs4>=4.12.2
  - backports>=1.0
  - conda-build>=3.26.0
  - coverage>=7.2.7
  - cython
  - flake8>=6.0.0
  - diff-cover>=7.7.0
  - pip>=23.2.1
  - pre-commit>=3.3.3
  # - pyppeteer>=1.0.2
  - python>=3.10.12
  - pytest>=7.4.0
  - pytest-asyncio>=0.16.0
  - setuptools>=68.0.0
  ### Packages used within HB and helping reduce the footprint of pip-installed packages
  - aiohttp>=3.8.5
  - asyncssh>=2.13.2
  - aioprocessing>=2.0.1
  - aioresponses>=0.7.4
  - aiounittest>=1.4.2
  - async-timeout>=4.0.2,<5
  - bidict>=0.22.1
  - cachetools>=5.3.1
  # - coinbase-advanced-py  # Requires websockets >=12, we don't actually use this package
  # - coincurve>=18.0.0
  - commlib-py>=0.11
  - cryptography>=41.0.2
  - dydxprotocol-v4-proto-py
  # - eth-account
  # - eth-keyfile
  # - eip712_structs>=1.1.1a1
  # - ethsnarks-loopring>=0.1.6a1
  # - injective-py
  - gql-with-aiohttp>=3.4.1
  - msgpack-python
  - numpy>=1.25.0
  # - numpy-base>=1.25.0
  - objgraph
  - pandas>=2.0.3
  - pandas-ta>=0.3.14b
  - prompt_toolkit>=3.0.39
  - protobuf>=4.23.3
  - psutil>=5.9.5
  - ptpython>=3.0.20
  # This needs to be restricted to <2.0 - tests fail otherwise
  - pydantic>=1.10.12
  - pyjwt>=2.3.0
  - pyperclip>=1.8.2
  - requests>=2.31.0
  - ruamel.yaml>=0.2.5
  - rust
  - safe-pysha3
  - scalecodec
  - scipy>=1.11.1
  - six>=1.16.0
  - sqlalchemy>=1.4.49 #,<1.4.99
  - substrate-interface
  # - signalr-client>=0.0.7
  - tabulate>=0.9.0
  - ujson>=5.7.0
  # This needs to be restricted to <2.0 - tests fail otherwise
  - urllib3>=1.26.15,<2.0
  - vega-python-sdk
  # - websockets>=10.4
  - xrpl-py>=4,<4.1.0
  - yaml>=0.2.5
  - zlib>=1.2.13
  #
  ### Packages required by pip packages that are not available on conda-forge/defaults
  ### These are installed via pip --no-deps to prevent them overriding the conda
  ### packages above (see pip_packages.txt file).
  ### Some care was taken to include as many conda packages as possible
  ### to reduce the number of pip-installed packages.
  # - pip:
  #     - eip712_structs==1.1.0
      # This tries to install the following pip packages, which happen to already be covered by conda packages
      # Requirement already satisfied: python-telegram-bot==12.4.2
      # Requirement already satisfied: future>=0.16.0
      # Requirement already satisfied: certifi
      # Requirement already satisfied: tornado>=5.1
      # Requirement already satisfied: cryptography
      # Requirement already satisfied: decorator>=4.4.0
      # Requirement already satisfied: cffi>=1.12
      # Requirement already satisfied: pycparser
